imports:
    - php

before_commands:
    - "composer install --prefer-source"

filter:
    excluded_paths:
        - 'vendor/*'
        - 'Tests/*'

tools:
    php_code_coverage: true
    php_analyzer:
        enabled:    true
        filter:
            excluded_paths: ['vendor', 'Tests']
    php_sim: true
    sensiolabs_security_checker: true
    php_loc:
        enabled: true
        excluded_dirs: ['vendor', 'Tests']
